# authors = ["James Mount"]
# channels = ["conda-forge","robostack-staging"]
# platforms = ["linux-64"]
#
[workspace]
name="rosdata"
authors = ["James Mount"]
channels = ["conda-forge","robostack-staging"]
platforms = ["linux-64"]
preview = ["pixi-build"] 
version = "0.1.0"

[package]
name = "rosdata"
version = "0.1.0"
authors = ["James Mount"]
description = "ROS data package"

[tasks]

[dependencies]
ros-noetic-desktop = "*"
ros-noetic-cv-bridge = "*"
ros-noetic-ros-numpy = "*"
rospkg = "*"
tabulate = "*"
imutils = "*"
rosdata = { path = "." }
spatialmath-python = ">=1.1.13,<2"
dill = ">=0.3.9,<0.4"
tqdm = ">=4.67.1,<5"
open3d = ">=0.18.0,<0.19"
treelib = ">=1.7.0,<2"


[package.build] 
backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "robostack-staging"
]

[package.host-dependencies]
ros-noetic-desktop = "*"
ros-noetic-cv-bridge = "*"
ros-noetic-ros-numpy = "*"
rospkg = "*"
tabulate = "*"
imutils = "*"
rosdata = { path = "." }
spatialmath-python = ">=1.1.13,<2"
dill = ">=0.3.9,<0.4"
tqdm = ">=4.67.1,<5"
open3d = ">=0.18.0,<0.19"
treelib = ">=1.7.0,<2"
hatchling = "==1.26.3"


[package.run-dependencies]
ros-noetic-desktop = "*"
ros-noetic-cv-bridge = "*"
ros-noetic-ros-numpy = "*"
rospkg = "*"
tabulate = "*"
imutils = "*"
rosdata = { path = "." }
spatialmath-python = ">=1.1.13,<2"
dill = ">=0.3.9,<0.4"
tqdm = ">=4.67.1,<5"
open3d = ">=0.18.0,<0.19"
treelib = ">=1.7.0,<2"
