# This workflow will:
#   

name: Documentation Build & Publish

# run workflow on push to main branch and pull requests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8' 
      #     cache: 'pip' # caching pip dependencies
      # - run: pip install sphinx sphinx-toolbox enum_tools sphinx_rtd_theme
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: rosdata_env.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
      - name: Build Sphinx Documentation
        shell: bash -l {0}
        run: |
          mamba install sphinx sphinx-toolbox enum_tools sphinx_rtd_theme 
          pip install .
          cd docs/
          make html
      # # runs make html
      # - uses: ammaraskar/sphinx-action@master
      #   with:
      #     pre-build-command: "apt-get update -y && apt-get install -y && pip install sphinx sphinx-toolbox  -y"
      #     docs-folder: "docs/"
      
      # Create an artifact of the html output.
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/build/html/

      # Publish built docs to gh-pages branch
      - name: Commit documentation changes
        run: |
          git clone https://github.com/qcr/rosdata.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}