# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: push

jobs:
  build:
    name: ${{matrix.os}} (Mambaforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        include:
          - os: ubuntu
            environment-file: rosdata_env.yml
            miniforge-variant: Mambaforge

    steps:
    - uses: actions/checkout@v3
    - name: Set up Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ${{ matrix.environment-file }}
        miniforge-variant: ${{ matrix.miniforge-variant }}
        miniforge-version: latest
        use-mamba: true
#    - name: Test Mamba
#      shell: bash -l {0}
#      run: |
#        mamba info
#        mamba list
#    - name: Lint with flake8
#      run: |
#        mamba install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pip install .
        mamba install -y pytest
        pytest
